In [1]:
import torch

x = torch.tensor([[1,2,3],[4,5,6]])
y = torch.tensor([[7, 8, 9],[10, 11, 12]])

print(x)
print(y)

f = 2 * x + y
print(f)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[ 7,  8,  9],
        [10, 11, 12]])
tensor([[ 9, 12, 15],
        [18, 21, 24]])
