In [3]:
import torch

shape = [2,3]
xzeros = torch.zeros(shape)
xones = torch.ones(shape)
xrnd = torch.rand(shape)

print(xzeros)
print(xones)
print(xrnd) # each time code runs new randoms value are generated

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3515, 0.3237, 0.0644],
        [0.7457, 0.1282, 0.4990]])


In [10]:
torch.manual_seed(12) # fix randoms values generated
print(torch.rand(shape))

tensor([[0.4657, 0.2328, 0.4527],
        [0.5871, 0.4086, 0.1272]])
