In [12]:
import torch
import numpy as np

y = torch.tensor([[7, 8, 9],[10, 11, 12]])

xnp = np.array([[1, 2, 3],[4, 5, 6]])
xtensor = torch.from_numpy(xnp)
f2 = xtensor + y
print(f2)
f2.type

tensor([[ 8, 10, 12],
        [14, 16, 18]])


<function Tensor.type>

In [19]:
print(f2.type()) # call the tensor type method
f2np = f2.numpy() # create an array from the tensor
type(f2np) # uses the python inbuilt type()

torch.LongTensor


numpy.ndarray

In [20]:
a = np.ones(3) 
t = torch.from_numpy(a)
b = t.numpy()
b[1] = 0
print(a[1] == b[1])
print(t)
# a, t, b share the same memory 
# if a value inside a specific array or a tensor is change 
# all objects change because they share the same memory

True
tensor([1., 0., 1.], dtype=torch.float64)


In [24]:
int8np = np.ones((2,3), dtype = np.int8)
bad = torch.from_numpy(int8np)
bad # Python 3.7 has problem to recognize 8 bits as tensor. 

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int8)

In [25]:
good = torch.from_numpy(int8np.astype(np.int32))
good.type()

'torch.IntTensor'

In [28]:
xint = torch.ones((2,3), dtype = torch.int)
print(xint)
xint.type() # by default the int type tensor in PyTorch is 32 bits

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


'torch.IntTensor'