In [5]:
import torch

x = torch.tensor([[1,2,3],[4,5,6]])
y = torch.tensor([[7, 8, 9],[10, 11, 12]])

print(x[0])
print(x[1])
print(x[1][0:2])
print(x[1][0:1])
print(x[1][0])
print(x[1][1])
print(x[1][2])

tensor([1, 2, 3])
tensor([4, 5, 6])
tensor([4, 5])
tensor([4])
tensor(4)
tensor(5)
tensor(6)


In [6]:
print(x.view(-1))
print(x.view(3,2))
print(x.view(6,1))
# This kind of operation not change a values in x (assignment operation)

tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])


In [7]:
print(x.view(3,-1))

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [8]:
print(x.transpose(0,1))

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [11]:
a = torch.ones(1, 2, 3, 4)
print(a.size())
print(a.transpose(0,3).transpose(1,2).size()) # swap axis in two steps
print(a.permute(3, 2, 1, 0).size())   # swap all axis at once

torch.Size([1, 2, 3, 4])
torch.Size([4, 3, 2, 1])
torch.Size([4, 3, 2, 1])
