In [1]:
import torch

x = torch.tensor([[1,2,3],[4,5,6]])
y = torch.tensor([[7, 8, 9],[10, 11, 12]])

print(x)
x.transpose_(1,0)
print(x)
# This kind of operation change a values in x (In place operation)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [3]:
x = torch.tensor([[1,2,3],[4,5,6]]) # set again because "x" shape change before
print(y)
y.add_(x*2)
print(y)

tensor([[ 7,  8,  9],
        [10, 11, 12]])
tensor([[ 9, 12, 15],
        [18, 21, 24]])
